### ISSUE TITLE
Subclassed Hash with overridden #initialize cannot be deserialized

### ISSUE THREAD

**Issue by mbklein** [tenderlove/psych#196]
```ruby
#!/usr/bin/env ruby

gem 'psych', '2.0.5'
require 'psych'

class HashThing < Hash
  attr :obj
  def initialize(obj)
    @obj = obj
  end
end

a = [1,2,3,4,5]
t1 = HashThing.new(a)
t2 = Psych.load(Psych.dump(t1))
puts t2.obj
```
The `YAML.load` line raises `ArgumentError: wrong number of arguments (0 for 1)`.

It only seems to be a problem with `Hash` descendants. `Array` and `String` both work as expected; I haven't bothered to test any other classes.

Tested with different combinations of the following:
* Ruby 1.9.3 (p429 and p545), 2.0.0 (p451), 2.1.0 (p0)
* Psych 1.2.2, 1.3.4, 2.0.5

Backtrace (from Ruby 2.1.0/Psych 2.0.5):

```
./psych_bug.rb:8:in `initialize': wrong number of arguments (0 for 1) (ArgumentError)
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/to_ruby.rb:263:in `new'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/to_ruby.rb:263:in `visit_Psych_Nodes_Mapping'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/visitor.rb:15:in `visit'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/visitor.rb:5:in `accept'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/to_ruby.rb:31:in `accept'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/to_ruby.rb:278:in `visit_Psych_Nodes_Document'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/visitor.rb:15:in `visit'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/visitor.rb:5:in `accept'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/visitors/to_ruby.rb:31:in `accept'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych/nodes/node.rb:37:in `to_ruby'
	from .../lib/ruby/gems/2.1.0/gems/psych-2.0.5/lib/psych.rb:246:in `load'
	from ./psych_bug.rb:15:in `<main>'
```

**Comment by tenderlove** [comment]
Seems it was because I was calling `new` on the `Hash` class, rather than `allocate`.
