### ISSUE TITLE
Error running Jekyll with psych gem installed

### ISSUE THREAD

**Issue by alexdiliberto** [tenderlove/psych#214]
There is some issue with psych (v2.0.8, 2.0.7, 2.0.6) that is causing an error when running Jekyll. Let me know if you guys think I should post an issue on the Jekyll github page as well or if you need any more information about my particular setup.

There is no issue on psych 2.0.5, jekyll will run just fine.

```sh
AlexBookPro2:alexdiliberto.github.io alex$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin13.0]
```

```sh
AlexBookPro2:alexdiliberto.github.io alex$ jekyll -v
jekyll 2.5.2
```

```sh
AlexBookPro2:alexdiliberto.github.io alex$ gem uninstall psych
Successfully uninstalled psych-2.0.7

AlexBookPro2:alexdiliberto.github.io alex$ gem install psych -v 2.0.6
Fetching: psych-2.0.6.gem (100%)
Building native extensions.  This could take a while...
Successfully installed psych-2.0.6
Parsing documentation for psych-2.0.6
Installing ri documentation for psych-2.0.6
Done installing documentation for psych after 1 seconds
1 gem installed

AlexBookPro2:alexdiliberto.github.io alex$ jekyll
/Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:4:in `<class:PsychResolver>': uninitialized constant Psych::Nodes (NameError)
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:2:in `<module:SafeYAML>'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/psych_resolver.rb:1:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:131:in `<module:SafeYAML>'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:26:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/lib/jekyll.rb:26:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Users/alex/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/jekyll-2.5.2/bin/jekyll:6:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.1.5/bin/jekyll:23:in `load'
	from /Users/alex/.rbenv/versions/2.1.5/bin/jekyll:23:in `<main>'

AlexBookPro2:alexdiliberto.github.io alex$ gem uninstall psych
Successfully uninstalled psych-2.0.6

AlexBookPro2:alexdiliberto.github.io alex$ gem install psych -v 2.0.5
Fetching: psych-2.0.5.gem (100%)
Building native extensions.  This could take a while...
Successfully installed psych-2.0.5
Parsing documentation for psych-2.0.5
Installing ri documentation for psych-2.0.5
Done installing documentation for psych after 1 seconds
1 gem installed

AlexBookPro2:alexdiliberto.github.io alex$ jekyll
jekyll 2.5.2 -- Jekyll is a blog-aware, static site generator in Ruby

Usage:

  jekyll <subcommand> [options]

Options:
        -s, --source [DIR]  Source directory (defaults to ./)
        -d, --destination [DIR]  Destination directory (defaults to ./_site)
            --safe         Safe mode (defaults to false)
        -p, --plugins PLUGINS_DIR1[,PLUGINS_DIR2[,...]]  Plugins directory (defaults to ./_plugins)
            --layouts DIR  Layouts directory (defaults to ./_layouts)
        -h, --help         Show this message
        -v, --version      Print the name and version
        -t, --trace        Show the full backtrace when an error occurs

Subcommands:
  build, b              Build your site
  docs                  Launch local server with docs for Jekyll v2.5.2
  doctor, hyde          Search site and print specific deprecation warnings
  help                  Show the help message, optionally for a given subcommand.
  new                   Creates a new Jekyll site scaffold in PATH
  serve, server, s      Serve your site locally

AlexBookPro2:alexdiliberto.github.io alex$ 

```

**Comment by tenderlove** [comment]
This looks like a bug in `safe_yaml`.
