### ISSUE TITLE
yaml and string beggining with a comma

### ISSUE THREAD

**Issue by Poil** [tenderlove/psych#240]
Hi,

Moneta store in the yaml backend without "protecting" with double quotes when it's need.

When we have a value begining with a comma it crash psych.rb

Content
```yaml
key: ,azezaeaz
```

Trace
```sh
Action failed with the following message: (<unknown>): did not find expected node content while parsing a block node at line 33 column 10
(See full trace by running task with --trace)
/usr/share/ruby/psych.rb:205:in `parse': (<unknown>): did not find expected node content while parsing a block node at line 33 column 10 (Psych::SyntaxError)
	from /usr/share/ruby/psych.rb:205:in `parse_stream'
	from /usr/share/ruby/psych.rb:153:in `parse'
	from /usr/share/ruby/psych.rb:129:in `load'
	from /usr/share/ruby/yaml/store.rb:61:in `load'
	from /usr/share/ruby/pstore.rb:395:in `load_data'
	from /usr/share/ruby/pstore.rb:327:in `transaction'
	from /usr/local/share/gems/gems/moneta-0.8.0/lib/moneta/adapters/pstore.rb:33:in `load'
	from /usr/local/share/gems/gems/moneta-0.8.0/lib/moneta/transformer.rb:88:in `load'
	from /usr/local/share/gems/gems/moneta-0.8.0/lib/moneta/mixins.rb:167:in `fetch'
	from /usr/local/share/gems/gems/trocla-0.1.1/lib/trocla.rb:35:in `get_password'
	from /usr/local/share/gems/gems/trocla-0.1.1/bin/trocla:54:in `get'
	from /usr/local/share/gems/gems/trocla-0.1.1/bin/trocla:114:in `<top (required)>'
	from /usr/local/bin/trocla:23:in `load'
	from /usr/local/bin/trocla:23:in `<main>'
```

Best regards,

Ref. https://github.com/minad/moneta/issues/83

**Comment by Poil** [comment]
I close this issue, only appear in case of ruby 1.8
