### ISSUE TITLE
Regex interpretting string incorrectly as an Integer

### ISSUE THREAD

**Issue by hackling** [tenderlove/psych#244]
Added to `test/pysch/test_scalar_scanner.rb`
``` ruby
    def test_numeric_strings_with_spaces
      [
        "16 1",
        "16 \n1 ",
        "16 \n1",
      ].each do |string|
        assert_equal string, ss.tokenize(string)
      end
    end
```

Test Failure
```
Run options: --seed 42160

# Running:

........E........

Finished in 0.004591s, 3703.2955 runs/s, 6970.9091 assertions/s.

  1) Error:
Psych::TestScalarScanner#test_numeric_strings_with_spaces:
ArgumentError: invalid value for Integer(): "16 \n1"
    /Users/nick/.rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/scalar_scanner.rb:117:in `Integer'
    /Users/nick/.rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/scalar_scanner.rb:117:in `parse_int'
    /Users/nick/.rubies/ruby-2.1.5/lib/ruby/2.1.0/psych/scalar_scanner.rb:105:in `tokenize'
    test/psych/test_scalar_scanner.rb:112:in `block in test_numeric_strings_with_spaces'
    test/psych/test_scalar_scanner.rb:111:in `each'
    test/psych/test_scalar_scanner.rb:111:in `test_numeric_strings_with_spaces'

17 runs, 32 assertions, 0 failures, 1 errors, 0 skips
```

---

Was playing around with it and it seems to be related to whether or not the string has been double or single quoted.
__scratch.rb__
``` ruby
INTEGER = /^(?:[-+]?0b[0-1_]+          (?# base 2)
              |[-+]?0[0-7_]+           (?# base 8)
              |[-+]?(?:0|[1-9][0-9_]*) (?# base 10)
              |[-+]?0x[0-9a-fA-F_]+    (?# base 16))$/x

puts(
    [
    "16",
    '16',
    "16 1",
    '16 1',
    "16 \n1",
    '16 \n1',
    "16 \r1",
    '16 \r1',
  ].map do |string|
      {
        string: string,
        match_data: INTEGER.match(string).inspect,
      }
  end
)
```

__result__
```
{:string=>"16", :match_data=>"#<MatchData \"16\">"}
{:string=>"16", :match_data=>"#<MatchData \"16\">"}
{:string=>"16 1", :match_data=>"nil"}
{:string=>"16 1", :match_data=>"nil"}
{:string=>"16 \n1", :match_data=>"#<MatchData \"1\">"}
{:string=>"16 \\n1", :match_data=>"nil"}
{:string=>"16 \r1", :match_data=>"nil"}
{:string=>"16 \\r1", :match_data=>"nil"}
```

**Comment by hackling** [comment]
Looks like this issue has already been resolved. 

I thought the issue was still existent from v2.0.5 in v.2.0.13. I wasn't using the rake task to run my spec, and so I was using the version of `Psych` that comes with ruby `2.1.5.`, which happens to be `v2.0.5`, when I thought I was on the current version.
