### ISSUE TITLE
Psych.dump fails to write UTF-8 to file

### ISSUE THREAD

**Issue by roysc** [tenderlove/psych#287]
```ruby
# coding: utf-8
require 'yaml'

h = {name: '李'}
YAML.dump(h, File.new('out.yml', 'w:utf-8'))
```
Fails with: `Encoding::UndefinedConversionError: "\xE5" from ASCII-8BIT to UTF-8`

**Comment by tenderlove** [comment]
The script you gave me works for me. Can you give me more information?

**Comment by JuanitoFatas** [comment]
I can reproduce with Ruby 2.1.9:

```
irb(main):001:0> RUBY_VERSION
=> "2.1.9"
irb(main):002:0> require 'yaml'; h = {name: '李'}; YAML.dump(h, File.new('out.yml', 'w:utf-8'))
Encoding::UndefinedConversionError: "\xE6" from ASCII-8BIT to UTF-8
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `write'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `end_document'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `visit_Psych_Nodes_Document'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `block in visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `each'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/nodes/node.rb:48:in `yaml'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych.rb:410:in `dump'
	from (irb):2
	from /Users/Juan/.rubies/ruby-2.1.9/bin/irb:11:in `<main>'
```

And Ruby 2.2.5:

```
irb(main):001:0> RUBY_VERSION
=> "2.2.5"
irb(main):002:0> require 'yaml'; h = {name: '李'}; YAML.dump(h, File.new('out.yml', 'w:utf-8'))
Encoding::UndefinedConversionError: "\xE6" from ASCII-8BIT to UTF-8
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:27:in `write'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:27:in `end_document'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:27:in `visit_Psych_Nodes_Document'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:20:in `block in visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:20:in `each'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/emitter.rb:20:in `visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych/nodes/node.rb:48:in `yaml'
	from /Users/Juan/.rubies/ruby-2.2.5/lib/ruby/2.2.0/psych.rb:410:in `dump'
	from (irb):2
	from /Users/Juan/.rubies/ruby-2.2.5/bin/irb:11:in `<main>'
```

🙇

**Comment by tenderlove** [comment]
@JuanitoFatas what is your "default_external" set to?

```
[aaron@TC ~]$ irb
irb(main):001:0> require 'yaml'; h = {name: '李'}; YAML.dump(h, File.new('out.yml', 'w:utf-8'))
=> #<File:out.yml>
irb(main):002:0> Encoding.default_external
=> #<Encoding:UTF-8>
irb(main):003:0> Encoding.default_internal
=> nil
irb(main):004:0>
```

**Comment by JuanitoFatas** [comment]
Also `#<Encoding:UTF-8>`:

```
irb(main):001:0> Encoding.default_external
=> #<Encoding:UTF-8>
irb(main):002:0> RUBY_VERSION
=> "2.2.5"
```

Thanks!

**Comment by JuanitoFatas** [comment]
I tried to write a test:

```ruby
def test_dump_chinese_string_to_file
  Tempfile.create(['utf8', 'yml'], :encoding => 'UTF-8') do |t|
    h = {'one' => '李'}
    Psych.dump(h, t)
    t.close
    assert_equal h, Psych.load_file(t.path)
  end
end
```

but when I run the test with 2.1.9, tests all passed.

While trying out at console still failing:

```
irb
irb(main):001:0> require "tempfile"; require "psych";
irb(main):002:0* Tempfile.create(['utf8', 'yml'], :encoding => 'UTF-8') do |t|
irb(main):003:1*     h = {'one' => '李'}
irb(main):004:1>     Psych.dump(h, t)
irb(main):005:1>     t.close
irb(main):006:1>     Psych.load_file(t.path)
irb(main):007:1>   end
Encoding::UndefinedConversionError: "\xE6" from ASCII-8BIT to UTF-8
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `write'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `end_document'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:27:in `visit_Psych_Nodes_Document'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `block in visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `each'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/emitter.rb:20:in `visit_Psych_Nodes_Stream'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:15:in `visit'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/visitors/visitor.rb:5:in `accept'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych/nodes/node.rb:48:in `yaml'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/psych.rb:410:in `dump'
	from (irb):4:in `block in irb_binding'
	from /Users/Juan/.rubies/ruby-2.1.9/lib/ruby/2.1.0/tempfile.rb:371:in `create'
	from (irb):2
	from /Users/Juan/.rubies/ruby-2.1.9/bin/irb:11:in `<main>'
```

**Comment by hsbt** [comment]
This was fixed in psych 2.0.16 (17e5d30991) and the reproduction works fine on current releases. Closing as resolved.
